### PR TITLE
Dynamic code added for stargazers and forkers as a sign of shoutout to contributors

### PR DESCRIPTION
**Pull request by yash982000**
And a spelling mistake too :)

### CODE REVIEW

**Comment by jounathaen** [comment]
It is always good to appreciate the contributors. But could you elaborate why you add the stargazers and forkers to the README? These especially are not contributors in my oppinion?

**Comment by yash982000** [comment]
@jounathaen True, stargazers are directly not contributors. Forkers might be. But, I will seperately do for the contributors and add it. Let me know if I should remove the stargazers.

**Comment by yash982000** [comment]
@jounathaen Another reason for this which I think is it seems to be good statistics when someone searches any project to contribute or take it as college work. For instance, I was highly impressed by the readme of this project at first and ultimately the project turns out to be good. In shirt, it may hep to attract more contributors.

**Comment by yash982000** [comment]
@jounathaen @stlankes Please let me know whatever changes to be done. I will be happy to do it.

**Comment by jounathaen** [comment]
But the statistics for stargazers and forks can easily be found in the upper right corner of the github page. If you want to add this feature, please limit it to contributors. I personally wouldn't be happy it if my profile is prominently shown on some project page, just because I starred or forked it.

**Comment by yash982000** [comment]
@jounathaen Yeah, completely understandable. I will do the required changes.

**Comment by yash982000** [comment]
@jounathaen Done. This is also dynamic but it won't allow redirecting to each contributor's profile since it's an image. I hope this is okay. Let me know if there are any changes or you can merge it. Thanks for guiding :)

**Comment by jounathaen** [comment]
Looks fine! Thanks for your contribution :+1:

**Comment by yash982000** [comment]
@jounathaen Great, thank you so much. I am loving contributing here. Thanks for the support and quick replies.

**Pull request merged**
